name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master
    - name: Zig Test
      run: zig build test
